### ISSUE TITLE
GUI Designs

### ISSUE THREAD

**Issue by DMNemec** [WickedChester/Project-1#2]

**Comment by WickedChester** [comment]
These are what I had in mind for the GUI's.

![admin_options](https://cloud.githubusercontent.com/assets/16946227/13273849/2a10d922-da6c-11e5-939d-bcfe669cb088.png)
![employee_creation](https://cloud.githubusercontent.com/assets/16946227/13273850/2a115b54-da6c-11e5-9434-87b6cb8eb143.png)
![employee_options](https://cloud.githubusercontent.com/assets/16946227/13273851/2a11c5ee-da6c-11e5-9af2-f59ab458de88.png)
![item_ admin](https://cloud.githubusercontent.com/assets/16946227/13273852/2a126d96-da6c-11e5-926e-07500f2cf0ef.png)
![item_ employee_view](https://cloud.githubusercontent.com/assets/16946227/13273853/2a138032-da6c-11e5-95ff-135f66dd029f.png)
![item_search](https://cloud.githubusercontent.com/assets/16946227/13273854/2a1655dc-da6c-11e5-9873-a7d0b0e801df.png)
![login](https://cloud.githubusercontent.com/assets/16946227/13273855/2a1ee1c0-da6c-11e5-9375-4e4ac4de1e1e.png)
