### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by DMNemec** [WickedChester/Project-1#3]
Design ways to store data in DB
![image_2](https://cloud.githubusercontent.com/assets/7027698/13199707/09d043f4-d7f2-11e5-8eb8-47e20f7e2105.jpg)
![image_3](https://cloud.githubusercontent.com/assets/7027698/13199708/09d2c5fc-d7f2-11e5-8b22-2615fa6b48e5.jpg)

**Comment by DMNemec** [comment]
- Employee
  - ID (String, restricted to numbers)
  - Password (alphanumeric)
  - Admin (boolean)
- Item_Price
  - ID*
  - Cost
  - Markup %
  - Discount %
- Item_Inventory
  - ID*
  - Number on Hand
  - Minimum on Hand
  - Ideal Amount
- Item_Category
  - ID*
  - Category
  - Category Discount
- Item_Name
  - ID*
  - Name
- Audit_Record
  - Audit_Trans_ID*
  - Type
    - Add/Remove Employees
    - Update Employee Info
    - Add/Remove Products
    - Discounts
    - Stocking
    - Price Changes
    - Sales
    - Transactions
    - Logins/Offs
    - Audit Log Accesses
    - Purchase Orders
  - Employee
  - Date

**Comment by sfolkerts** [comment]
Database Tables MYSQL code


create table Employee
(
User_ID int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Password varchar(255),
Admin_Rights Boolean );

Create Unique Index Employee_Index on Employee (User_ID);




create table Item_Price
(
Item_ID int PRIMARY KEY,
Cost decimal(2),
Markup_Per decimal(2),
Discount_Per  decimal(2),
FOREIGN KEY (Item_ID) REFERENCES Item_Name(Item_ID));

Create Unique Index Item_Price_ID_Index on Item_Price (Item_ID);



 


create table Item_Inventory
(
Item_ID int PRIMARY KEY,
Num_On_Hand int,
Min_On_Hand int,
Ideal_Amount  int,
FOREIGN KEY (Item_ID) REFERENCES Item_Name(Item_ID));

Create Unique Index Item_Inventory_ID_Index on Item_Inventory (Item_ID);




create table Item_Category
(
Item_ID int PRIMARY KEY,
Category varchar(50),
Category_Discount decimal(2),
FOREIGN KEY (Item_ID) REFERENCES Item_Name(Item_ID));

Create  Unique Index Item_Category_ID_Index on Item_Category (Item_ID);




Create table Item_Name
(
Item_ID int  AUTO_INCREMENT PRIMARY KEY,
Item_Name varchar(50));

Create Unique Index Item_Name_ID_Index on Item_Name(Item_ID);

**Comment by sfolkerts** [comment]
I added these table to the database. The database is called  SE_spr16_F_db on student.cs.uni.edu.

**Comment by DMNemec** [comment]
completed
- Audit_Record
- Audit_Login
- Audit_Employment (combined login and update info)
