### ISSUE TITLE
Questions for Customer

### ISSUE THREAD

**Issue by hellHounds8793** [WickedChester/Project-1#6]
1) Employee/Admin log in 
2) Store Purchase Order
           -what information do you want?
            -do you want it emailed? to where?
3) What percentage for discounts?
4) Custom abbreviations of items on the receipt?
5) Assigned passwords or be able to change employee's password?
6) What categories for the items do you want?
7) What minimum keep on hand ?

**Comment by DMNemec** [comment]
1. Employee/Admin log in. Numbers or names for logins, same screen okay?
- Employee numbers
- Same screen, different options
2. Store Purchase Order
- what information do you want?
  - Name, price, quantity
  - Export data is up to us
- do you want it emailed? to where?
  - Email is set in admin panel
3. What percentage for discounts?
- change discounts by admins
- category discounts override item discounts
4. Custom abbreviations of items on the receipt?
- slicing off names is fine
5. Assigned passwords or be able to change employee's password?
- employees can change their own password
6. What categories for the items do you want?
- mom and pop pet store (cats, fish, dogs)
7. What minimum keep on hand ?
- be able to modify
